(function(){
  "use strict";

  var worker=null, runToken=0, liveTimer=null, liveStart=0, liveLabel="";
  var activeDisplayOutputs=Object.create(null), sectionState=Object.create(null);
  var activeDefinitions=Object.create(null), activeCatalogueEntry=null;
  var coordinateNames=["u","v","x","y"];
  var COMPONENT_COLLAPSE_THRESHOLD=360, SUMMARY_COLLAPSE_THRESHOLD=1100;
  var KNOWN_FUNCTIONS={sqrt:1,exp:1,sin:1,cos:1,tan:1,sinh:1,cosh:1,tanh:1,log:1,ln:1,abs:1,asin:1,acos:1,atan:1,atan2:1,min:1,max:1,sign:1};
  var BUILTIN_CONSTANTS={pi:1,e:1,i:1,Infinity:1};
  var SECTION_KEYS={metric:"metric",inverse:"inverse",cartan:"cartan",spray:"spray",nonlinear:"nonlinear",christoffel:"connections",berwald:"connections",chern:"connections",curvature:"curvature",deviation:"deviation",ricci:"ricci",affineCurvature:"affine",affineRicci:"affine"};
  var PLUS_VALIDATION={minkowski:"Riemann = 0; Ric = 0",schwarzschild:"Ric = 0","barriola-vilenkin":"R = -2(1-k²)/(k² r²)","bertotti-kasner":"Ric = -Λ g; R = -4Λ","bessel-wave":"Vacuum: Ric = 0","cosmic-string-schwarzschild":"Ric = 0 away from the string",ernst:"Electrovac trace: R = 0",frw:"R = -6(a a¨ + a˙² + k)/a²",godel:"R = +1/a²",halilsoy:"Vacuum: Ric = 0",jnw:"Catalogue Ricci scalar with the overall sign converted to (+---)",kasner:"Ric = 0 under Kasner constraints",kerr:"Ric = 0",kottler:"Ric = -Λ g; R = -4Λ","morris-thorne":"R = +2 b0²/(b0²+l²)²","oppenheimer-snyder":"Exterior Ric = 0","petrov-ai":"Vacuum: Ric = 0","petrov-aii":"Vacuum: Ric = 0","petrov-aiii":"Vacuum: Ric = 0","petrov-bi":"Vacuum: Ric = 0","petrov-bii":"Vacuum: Ric = 0","petrov-biii":"Vacuum: Ric = 0","petrov-c":"Vacuum: Ric = 0","plane-wave":"Vacuum when p''/p + q''/q = 0","reissner-nordstrom":"Electrovac trace: R = 0",desitter:"Ric = -3H² g; R = -12H²","spinning-string":"Ric = 0 away from the axis","sultana-dyer":"Catalogue (+---) Ricci scalar/components checked","taub-nut":"Ric = 0",alcubierre:"Metric form checked; converted to (+---)"};

  function el(id){return document.getElementById(id);}
  function qa(sel,root){return Array.prototype.slice.call((root||document).querySelectorAll(sel));}
  function esc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");}
  function fmt(ms){if(ms<1000)return ms.toFixed(0)+" ms";if(ms<60000)return(ms/1000).toFixed(ms<10000?2:1)+" s";return Math.floor(ms/60000)+"m "+((ms%60000)/1000).toFixed(1)+"s";}
  function dimension(){return Number(el("dimension").value);}
  function currentInputMode(){var n=document.querySelector('input[name="inputMode"]:checked');return n?n.value:"metric";}
  function currentGeometryMode(){var n=document.querySelector('input[name="geometryMode"]:checked');return n?n.value:"riemannian";}
  function setStatus(text,type){var n=el("status");if(!n)return;n.textContent=text;n.className="calc-status"+(type?" is-"+type:"");}
  function stopLive(){if(liveTimer){clearInterval(liveTimer);liveTimer=null;}}
  function updateLive(){var n=el("live-step");if(n)n.textContent=liveLabel+" · "+fmt(performance.now()-liveStart);}
  function startLive(label){stopLive();liveLabel=label;liveStart=performance.now();updateLive();liveTimer=setInterval(updateLive,100);}
  function typeset(node){if(window.MathJax&&window.MathJax.typesetPromise)return window.MathJax.typesetPromise([node]).catch(function(){});return Promise.resolve();}

  function coordTex(name){var greek={theta:"\\theta",phi:"\\phi",psi:"\\psi",eta:"\\eta",rho:"\\rho",tau:"\\tau",sigma:"\\sigma"};if(greek[name])return greek[name];if(/^[A-Za-z]$/.test(name))return name;return "\\mathrm{"+String(name).replace(/[^A-Za-z0-9_]/g,"")+"}";}
  function fiberName(name){return "y_"+name;}
  function currentCoords(){return qa(".coordinate-input",el("coordinateFields")).map(function(n){return n.value.trim();});}
  function validSymbol(name){try{var n=math.parse(name);return !!(n&&n.isSymbolNode&&n.name===name);}catch(e){return false;}}
  function validateCoords(names){var seen=Object.create(null);names.forEach(function(name,i){if(!name)throw new Error("Coordinate "+(i+1)+" is empty.");if(!validSymbol(name))throw new Error("‘"+name+"’ is not a valid coordinate symbol.");if(seen[name])throw new Error("Coordinate names must be unique.");seen[name]=1;});return names;}
  function renameSymbolInExpression(text,oldName,newName){if(!text||oldName===newName)return text;try{var map={};map[oldName]=newName;map[fiberName(oldName)]=fiberName(newName);map["v_"+oldName]="v_"+newName;return math.parse(text).transform(function(child){if(child&&child.isSymbolNode&&map[child.name])return math.parse(map[child.name]);return child;}).toString({parenthesis:"auto"});}catch(e){return text;}}
  function renameCoordinateEverywhere(oldName,newName){qa(".metric-entry,.oneform-entry").forEach(function(n){n.value=renameSymbolInExpression(n.value,oldName,newName);});var lag=el("lagrangian");if(lag)lag.value=renameSymbolInExpression(lag.value,oldName,newName);var f=el("functionsInput");if(f)f.value=f.value.replace(new RegExp("\\b"+oldName+"\\b","g"),newName);}
  function renderCoordinates(names){var n=dimension(),old=names||coordinateNames||[],host=el("coordinateFields");host.innerHTML="";coordinateNames=[];for(var i=0;i<n;i++){var name=old[i]||("x"+(i+1));coordinateNames.push(name);var label=document.createElement("label");label.className="coordinate-item";label.innerHTML='<span>x<sup>'+(i+1)+'</sup></span><input class="coordinate-input" data-index="'+i+'" value="'+esc(name)+'" aria-label="Coordinate '+(i+1)+'">';host.appendChild(label);(function(input,index,previous){input.addEventListener("change",function(){var next=input.value.trim();try{validateCoords(currentCoords());}catch(err){input.value=previous;setStatus(err.message,"error");return;}if(next!==previous){renameCoordinateEverywhere(previous,next);coordinateNames[index]=next;refreshAxes();updateNotationHint();previous=next;}});})(label.querySelector("input"),i,name);}refreshAxes();updateNotationHint();}
  function refreshAxes(){var coords=currentCoords(),n=dimension(),axes=qa(".matrix-axis",el("metricGrid"));if(axes.length>=2*n){for(var i=0;i<n;i++){axes[i].textContent=coords[i]||("x"+(i+1));axes[n+i].textContent=coords[i]||("x"+(i+1));}}qa(".oneform-cell",el("oneFormGrid")).forEach(function(cell,i){var s=cell.querySelector("span");if(s)s.innerHTML="b<sub>"+esc(coords[i]||String(i+1))+"</sub>";});}
  function updateNotationHint(){var c=currentCoords();el("fiberHint").textContent="Fiber coordinates: "+c.map(fiberName).join(", ")+". A call such as a("+(c[0]||"t")+") is treated as a coordinate-dependent function; a bare symbol such as M is a constant.";}

  function snapshotMatrix(){var out=[];qa(".metric-entry",el("metricGrid")).forEach(function(c){var i=+c.dataset.i,j=+c.dataset.j;if(!out[i])out[i]=[];out[i][j]=c.value;});return out;}
  function snapshotOneForm(){var out=[];qa(".oneform-entry",el("oneFormGrid")).forEach(function(c){out[+c.dataset.i]=c.value;});return out;}
  function resizeMatrix(values){var n=dimension(),host=el("metricGrid"),old=values||[];host.innerHTML="";host.style.setProperty("--matrix-n",String(n));var blank=document.createElement("div");blank.className="matrix-corner";host.appendChild(blank);for(var c=0;c<n;c++){var h=document.createElement("div");h.className="matrix-axis";h.textContent=(coordinateNames[c]||String(c+1));host.appendChild(h);}for(var i=0;i<n;i++){var rh=document.createElement("div");rh.className="matrix-axis";rh.textContent=(coordinateNames[i]||String(i+1));host.appendChild(rh);for(var j=0;j<n;j++){var wrap=document.createElement("label");wrap.className="matrix-cell";var input=document.createElement("input");input.type="text";input.className="metric-entry";input.dataset.i=i;input.dataset.j=j;input.autocomplete="off";input.spellcheck=false;input.value=(old[i]&&old[i][j]!==undefined)?old[i][j]:(i===j?"1":"0");var sub=document.createElement("span");sub.textContent="g"+(i+1)+(j+1);wrap.appendChild(input);wrap.appendChild(sub);host.appendChild(wrap);}}qa(".metric-entry",host).forEach(function(input){input.addEventListener("input",function(){var i=+input.dataset.i,j=+input.dataset.j;if(i===j)return;var m=host.querySelector('.metric-entry[data-i="'+j+'"][data-j="'+i+'"]');if(m&&m.value!==input.value)m.value=input.value;});input.addEventListener("focus",function(){input.select();});});refreshAxes();}
  function resizeOneForm(values){var n=dimension(),host=el("oneFormGrid"),old=values||[];host.innerHTML="";host.style.setProperty("--vector-n",String(n));for(var i=0;i<n;i++){var wrap=document.createElement("label");wrap.className="oneform-cell";var tag=document.createElement("span");tag.innerHTML="b<sub>"+esc(coordinateNames[i]||String(i+1))+"</sub>";var input=document.createElement("input");input.type="text";input.className="oneform-entry";input.dataset.i=i;input.value=old[i]!==undefined?old[i]:"0";input.autocomplete="off";input.spellcheck=false;wrap.appendChild(tag);wrap.appendChild(input);host.appendChild(wrap);input.addEventListener("focus",function(){this.select();});}}
  function collectGridValues(){var n=dimension(),out=[];for(var i=0;i<n;i++){out[i]=[];for(var j=0;j<n;j++){var c=document.querySelector('.metric-entry[data-i="'+i+'"][data-j="'+j+'"]');out[i][j]=c?c.value:"0";}}return out;}
  function collectOneForm(){var n=dimension(),out=[];for(var i=0;i<n;i++){var c=document.querySelector('.oneform-entry[data-i="'+i+'"]');out[i]=c?c.value:"0";}return out;}
  function setMatrix(v){resizeMatrix(v);} function setOneForm(v){resizeOneForm(v);}

  function setInputMode(value){var r=document.querySelector('input[name="inputMode"][value="'+value+'"]');if(r){r.checked=true;updateMode();}}
  function setGeometryMode(value){var r=document.querySelector('input[name="geometryMode"][value="'+value+'"]');if(r){r.checked=true;updateAlphaBetaVisibility();}}
  function updateMode(){var metric=currentInputMode()==="metric";el("lagrangianInputPanel").hidden=metric;el("metricInputPanel").hidden=!metric;el("metricOutputLabel").textContent=metric?"Metric / fundamental tensor":"Fundamental tensor";updateAlphaBetaVisibility();}
  function updateAlphaBetaVisibility(){var show=currentInputMode()==="metric"&&currentGeometryMode()==="alphabeta";el("alphaBetaPanel").hidden=!show;el("plainMetricHint").hidden=show||currentInputMode()!=="metric";updateMVisibility();updateFormulaPreview();}
  function updateMVisibility(){el("mParameterWrap").hidden=el("alphaBetaType").value!=="mkropina";}
  function updateFormulaPreview(){var t=el("alphaBetaType").value,f=t==="randers"?"F=\\alpha+\\beta":t==="kropina"?"F=\\frac{\\alpha^2}{\\beta}":t==="mkropina"?"F=\\alpha^{1+m}\\beta^{-m}":"F=\\frac{\\alpha^2}{\\alpha-\\beta}";el("alphaBetaFormula").innerHTML="\\["+f+"\\]";typeset(el("alphaBetaFormula"));}

  function splitTopLevel(text){var out=[],buf="",depth=0;String(text||"").split("").forEach(function(ch){if(ch==="(")depth++;else if(ch===")")depth=Math.max(0,depth-1);if((ch===","||ch==="\n"||ch===";")&&depth===0){if(buf.trim())out.push(buf.trim());buf="";}else buf+=ch;});if(buf.trim())out.push(buf.trim());return out;}
  function parseConstants(){var out=Object.create(null);splitTopLevel(el("constantsInput").value).forEach(function(x){var n=x.trim();if(n&&validSymbol(n))out[n]=1;});return out;}
  function parseFunctionDeclarations(){var out=Object.create(null);splitTopLevel(el("functionsInput").value).forEach(function(part){var m=/^([A-Za-z_][A-Za-z0-9_]*)\s*\((.*)\)$/.exec(part);if(!m)return;out[m[1]]={name:m[1],args:splitTopLevel(m[2])};});return out;}
  function expandDefinitions(expr,defs){var text=String(expr),names=Object.keys(defs||{});if(!names.length)return text;for(var pass=0;pass<8;pass++){var changed=false,node=math.parse(text).transform(function(child){if(child&&child.isSymbolNode&&Object.prototype.hasOwnProperty.call(defs,child.name)){changed=true;return math.parse("("+defs[child.name]+")");}return child;});text=node.toString({parenthesis:"auto"});if(!changed)break;}return text;}
  function collectRawExpressions(){var out=[];if(currentInputMode()==="lagrangian")out.push(el("lagrangian").value);else{collectGridValues().forEach(function(r){r.forEach(function(x){out.push(x);});});if(currentGeometryMode()==="alphabeta")collectOneForm().forEach(function(x){out.push(x);});}return out;}
  function inferNotation(expressions){var coords=currentCoords(),coordSet=Object.create(null),fiberSet=Object.create(null);coords.forEach(function(c){coordSet[c]=1;fiberSet[fiberName(c)]=1;fiberSet["v_"+c]=1;});var fnNames=Object.create(null),fnSigs=Object.create(null),symbols=Object.create(null);expressions.forEach(function(raw){var text,node;try{text=expandDefinitions(raw,activeDefinitions);node=math.parse(text);}catch(e){return;}node.traverse(function(child){if(child&&child.isFunctionNode&&child.fn&&child.fn.isSymbolNode&&!KNOWN_FUNCTIONS[child.fn.name]){var args=child.args.map(function(a){return a.toString({parenthesis:"auto"});});fnNames[child.fn.name]=1;fnSigs[child.fn.name+"("+args.join(",")+")"]=1;}});node.traverse(function(child){if(child&&child.isSymbolNode){var name=child.name;if(coordSet[name]||fiberSet[name]||KNOWN_FUNCTIONS[name]||BUILTIN_CONSTANTS[name]||fnNames[name]||Object.prototype.hasOwnProperty.call(activeDefinitions,name))return;symbols[name]=1;}});});var existingC=parseConstants(),existingF=parseFunctionDeclarations();Object.keys(existingC).forEach(function(k){symbols[k]=1;});Object.keys(existingF).forEach(function(k){delete symbols[k];if(!fnNames[k])fnSigs[k+"("+existingF[k].args.join(",")+")"]=1;});el("constantsInput").value=Object.keys(symbols).sort().join(", ");el("functionsInput").value=Object.keys(fnSigs).sort().join(", ");}

  function makeTranslationContext(){return {coords:validateCoords(currentCoords()),functions:[],functionByKey:Object.create(null),constants:parseConstants(),declaredFunctions:parseFunctionDeclarations()};}
  function displayInternalArg(expr,coords){var s=String(expr);for(var i=coords.length;i>=1;i--)s=s.replace(new RegExp("\\bx"+i+"\\b","g"),coords[i-1]);return s;}
  function translateExpression(expr,ctx,allowFiber){var text=expandDefinitions(expr,activeDefinitions),node=math.parse(text),symbolMap=Object.create(null);ctx.coords.forEach(function(name,i){symbolMap[name]="x"+(i+1);if(allowFiber){symbolMap[fiberName(name)]="y"+(i+1);symbolMap["v_"+name]="y"+(i+1);}});node=node.transform(function(child){if(child&&child.isSymbolNode&&symbolMap[child.name])return math.parse(symbolMap[child.name]);return child;});node=node.transform(function(child){if(!child||!child.isFunctionNode||!child.fn||!child.fn.isSymbolNode)return child;var name=child.fn.name;if(KNOWN_FUNCTIONS[name])return child;if(ctx.constants[name])throw new Error(name+" is declared as a constant but is used as a function.");var args=child.args.map(function(a){return a.toString({parenthesis:"auto"});}),key=name+"\u0000"+args.join("\u0001"),found=ctx.functionByKey[key];if(!found){found={token:"__uf"+ctx.functions.length,name:name,args:args,argLabels:args.map(function(a){return displayInternalArg(a,ctx.coords);})};ctx.functionByKey[key]=found;ctx.functions.push(found);}return math.parse(found.token);});var functionTokens=Object.create(null);ctx.functions.forEach(function(f){functionTokens[f.token]=1;});node.traverse(function(child){if(!child||!child.isSymbolNode)return;var name=child.name;if(/^x\d+$/.test(name)||/^y\d+$/.test(name)||functionTokens[name]||BUILTIN_CONSTANTS[name]||ctx.constants[name])return;if(/^__uf\d+/.test(name))return;if(KNOWN_FUNCTIONS[name])return;throw new Error("Undeclared symbol ‘"+name+"’. Add it under Constants, or write it as a function such as "+name+"("+ctx.coords[0]+").");});return node.toString({parenthesis:"auto"});}
  function functionDisplay(token,ctx){var m=/^__uf(\d+)(?:_d([0-9_]+))?$/.exec(token);if(!m)return token;var f=ctx.functions[+m[1]];if(!f)return token;if(!m[2])return f.name+"("+f.argLabels.join(",")+")";var inds=m[2].split("_").map(Number),labs=[];inds.forEach(function(idx){var a=f.argLabels[idx-1]||("s"+idx);labs.push(/^[A-Za-z_][A-Za-z0-9_]*$/.test(a)?a:(f.argLabels.length===1?"s":"s"+idx));});return f.name+"_"+labs.join("_");}
  function displayExpression(expr,ctx){if(expr===undefined||expr===null)return expr;var s=String(expr);s=s.replace(/__uf\d+(?:_d[0-9_]+)?/g,function(t){return functionDisplay(t,ctx);});for(var i=ctx.coords.length;i>=1;i--){s=s.replace(new RegExp("\\by"+i+"\\b","g"),fiberName(ctx.coords[i-1]));s=s.replace(new RegExp("\\bx"+i+"\\b","g"),ctx.coords[i-1]);}return s;}
  function translateSummary(summary,ctx){if(!summary)return summary;var out={};Object.keys(summary).forEach(function(k){var v=summary[k];if(Array.isArray(v))out[k]=v.map(function(row){return Array.isArray(row)?row.map(function(x){return displayExpression(x,ctx);}):displayExpression(row,ctx);});else if(typeof v==="string")out[k]=displayExpression(v,ctx);else out[k]=v;});return out;}

  function collectOutputs(){var o=Object.create(null);qa("[data-output]").forEach(function(n){o[n.dataset.output]=!!n.checked;});return o;}
  function dependencyOutputs(selected){var o={};Object.keys(selected).forEach(function(k){o[k]=!!selected[k];});function need(k){o[k]=true;}if(o.inverse)need("metric");if(o.cartan)need("metric");if(o.spray){need("metric");need("inverse");}if(o.nonlinear){need("metric");need("inverse");need("spray");}if(o.connections){need("metric");need("inverse");need("spray");need("nonlinear");}if(o.curvature){need("metric");need("inverse");need("spray");need("nonlinear");need("connections");}if(o.deviation){need("metric");need("inverse");need("spray");need("nonlinear");need("connections");need("curvature");}if(o.ricci){need("metric");need("inverse");need("spray");need("nonlinear");need("connections");need("curvature");}if(o.affine){need("metric");need("inverse");need("connections");}return o;}
  function updateSelectionCount(){var c=qa("[data-output]:checked").length;el("selectionCount").textContent=c+" selected";}
  function setAllOutputs(v){qa("[data-output]").forEach(function(n){n.checked=v;});updateSelectionCount();}
  function selectEssentials(){var k={metric:1,inverse:1,connections:1,affine:1,ricci:1};qa("[data-output]").forEach(function(n){n.checked=!!k[n.dataset.output];});updateSelectionCount();}

  function payload(){var n=dimension(),mode=currentInputMode(),outputs=collectOutputs();if(!Object.keys(outputs).some(function(k){return outputs[k];}))throw new Error("Select at least one quantity to calculate.");inferNotation(collectRawExpressions());var ctx=makeTranslationContext(),out={n:n,inputType:mode,outputs:dependencyOutputs(outputs)},rawDisplay=outputs;if(mode==="lagrangian"){var L=el("lagrangian").value.trim();if(!L)throw new Error("Enter a Finsler Lagrangian.");out.L=translateExpression(L,ctx,true);}else{out.metricEntries=collectGridValues().map(function(r){return r.map(function(v){return translateExpression(v,ctx,false);});});var ab=currentGeometryMode()==="alphabeta";out.alphaBeta={enabled:ab};if(ab){out.alphaBeta.type=el("alphaBetaType").value;out.alphaBeta.b=collectOneForm().map(function(v){return translateExpression(v,ctx,false);});out.alphaBeta.m=el("mParameter").value.trim();}}out.symbolicFunctions=ctx.functions;return {workerPayload:out,displayOutputs:rawDisplay,context:ctx};}

  function prettyResultTex(text){
  var s=String(text);
  s=s.replace(/([A-Za-z][A-Za-z0-9]*)\\_([A-Za-z0-9]+)/g,"$1_{$2}");
  var fn="\\\\(?:sin|cos|tan|sinh|cosh|tanh)";
  var arg="(?:\\\\[A-Za-z]+|[A-Za-z](?:_\\{[A-Za-z0-9]+\\})?)";
  s=s.replace(new RegExp("\\{("+fn+")\\\\left\\(\\s*("+arg+")\\s*\\\\right\\)\\}\\s*\\^\\s*\\{([^{}]+)\\}","g"),"$1^{$3} $2");
  s=s.replace(new RegExp("("+fn+")\\s*\\^\\s*\\{([^{}]+)\\}\\s*\\\\left\\(\\s*("+arg+")\\s*\\\\right\\)","g"),"$1^{$2} $3");
  s=s.replace(new RegExp("("+fn+")\\\\left\\(\\s*("+arg+")\\s*\\\\right\\)\\s*\\^\\s*\\{([^{}]+)\\}","g"),"$1^{$3} $2");
  s=s.replace(new RegExp("("+fn+")\\\\left\\(\\s*("+arg+")\\s*\\\\right\\)","g"),"$1 $2");
  return s;
}
function tex(expr){try{return prettyResultTex(math.parse(String(expr)).toTex({parenthesis:"auto"}));}catch(e){return "\\\\text{"+esc(expr).replace(/[{}]/g,"")+"}";}}
  function displayLabel(label,coords){function c(i){return coordTex(coords[Number(i)-1]||("x"+i));}var s=String(label);s=s.replace(/g_\{(\d)(\d)\}/g,function(_,a,b){return "g_{"+c(a)+c(b)+"}";});s=s.replace(/g\^\{(\d)(\d)\}/g,function(_,a,b){return "g^{"+c(a)+c(b)+"}";});s=s.replace(/C_\{(\d)(\d)(\d)\}/g,function(_,a,b,d){return "C_{"+c(a)+c(b)+c(d)+"}";});s=s.replace(/G\^\{(\d)\}/g,function(_,a){return "G^{"+c(a)+"}";});s=s.replace(/N\^\{(\d)\}\{\}_\{(\d)\}/g,function(_,a,b){return "N^{"+c(a)+"}{}_{"+c(b)+"}";});s=s.replace(/\\Gamma\^\{(\d)\}\{\}_\{(\d)(\d)\}/g,function(_,a,b,d){return "\\Gamma^{"+c(a)+"}{}_{"+c(b)+c(d)+"}";});s=s.replace(/\^B\\Gamma\^\{(\d)\}\{\}_\{(\d)(\d)\}/g,function(_,a,b,d){return "{}^B\\Gamma^{"+c(a)+"}{}_{"+c(b)+c(d)+"}";});s=s.replace(/\^C\\Gamma\^\{(\d)\}\{\}_\{(\d)(\d)\}/g,function(_,a,b,d){return "{}^C\\Gamma^{"+c(a)+"}{}_{"+c(b)+c(d)+"}";});s=s.replace(/\\bar R\^\{(\d)\}\{\}_\{(\d)(\d)(\d)\}/g,function(_,a,b,d,e){return "\\bar R^{"+c(a)+"}{}_{"+c(b)+c(d)+c(e)+"}";});s=s.replace(/R\^\{(\d)\}\{\}_\{(\d)(\d)\}/g,function(_,a,b,d){return "R^{"+c(a)+"}{}_{"+c(b)+c(d)+"}";});s=s.replace(/R\^\{(\d)\}\{\}_\{(\d)\}/g,function(_,a,b){return "R^{"+c(a)+"}{}_{"+c(b)+"}";});s=s.replace(/R_\{(\d)(\d)\}/g,function(_,a,b){return "R_{"+c(a)+c(b)+"}";});s=s.replace(/\\bar R_\{(\d)(\d)\}/g,function(_,a,b){return "\\bar R_{"+c(a)+c(b)+"}";});return s;}
  function isZeroValue(v){var s=String(v).replace(/\s+/g,"");if(/^-?0(?:\.0+)?$/.test(s))return true;try{var z=math.simplify(v).toString().replace(/\s+/g,"");return /^-?0(?:\.0+)?$/.test(z);}catch(e){return false;}}
  function matrixAllZero(m){for(var i=0;i<m.length;i++)for(var j=0;j<m[i].length;j++)if(!isZeroValue(m[i][j]))return false;return true;}

  function prepareResults(){sectionState=Object.create(null);el("results").innerHTML='<section class="progress-card" id="calculation-progress"><div class="progress-top"><div><span class="section-kicker">Calculation</span><h2>Progress</h2></div><span class="path-pill" id="path-label">Starting…</span></div><div class="live-step" id="live-step">Preparing symbolic engine…</div><details class="timing-details"><summary>Timing log</summary><div id="timing-log" class="timing-log"></div></details></section><div id="progressive-sections" class="results-stack"></div>';el("results").scrollIntoView({behavior:"smooth",block:"start"});}
  function logTiming(text){var log=el("timing-log");if(!log)return;var r=document.createElement("div");r.className="timing-row";r.textContent=text;log.appendChild(r);}
  function ensureSection(key,title,meta){var id="section-"+key,n=el(id);if(n)return n;n=document.createElement("section");n.id=id;n.className="result-card progressive-result";n.innerHTML='<div class="result-heading"><div><span class="section-kicker">Result</span><h2>'+esc(title)+'</h2><p>'+esc(meta||"")+'</p></div><span class="result-meta" data-time>Working…</span></div><div class="component-list" data-components></div><div class="empty-components" data-empty hidden>All components vanish.</div><div class="section-summary" data-summary></div>';el("progressive-sections").appendChild(n);sectionState[key]={nonzero:0};return n;}
  function buildExpandableMath(host,label,value,threshold){var raw=String(value),size=raw.length;if(size<=threshold){host.innerHTML='<div class="component-formula">\\['+label+'='+tex(raw)+'\\]</div>';typeset(host);return;}host.innerHTML='<div class="expression-summary"><div><strong>\\('+label+'\\)</strong><span>'+size.toLocaleString()+' characters · simplified result hidden</span></div><button type="button" class="expression-toggle" aria-expanded="false">Expand</button></div><div class="expanded-expression" hidden><div class="sticky-collapse-bar"><button type="button" class="sticky-collapse-button">Collapse</button></div><div class="expanded-math-host"></div></div>';var summary=host.querySelector(".expression-summary"),expanded=host.querySelector(".expanded-expression"),mathHost=host.querySelector(".expanded-math-host"),button=host.querySelector(".expression-toggle"),sticky=host.querySelector(".sticky-collapse-button"),rendered=false;typeset(summary);function toggle(open){if(open){if(!rendered){mathHost.innerHTML='<div class="math-block">\\['+label+'='+tex(raw)+'\\]</div>';rendered=true;typeset(mathHost);}expanded.hidden=false;button.setAttribute("aria-expanded","true");button.textContent="Collapse";}else{expanded.hidden=true;button.setAttribute("aria-expanded","false");button.textContent="Expand";button.scrollIntoView({block:"nearest"});}}button.addEventListener("click",function(){toggle(button.getAttribute("aria-expanded")!=="true");});sticky.addEventListener("click",function(){toggle(false);});}
  function appendComponent(msg,ctx){var sec=el("section-"+msg.section);if(!sec)return;var label=displayLabel(msg.label,ctx.coords);if(isZeroValue(msg.value))return;sectionState[msg.section].nonzero++;var row=document.createElement("div");row.className="component-row";var host=document.createElement("div");host.className="component-main";var timing=document.createElement("span");timing.className="component-time";timing.textContent=fmt(msg.elapsedMs);row.appendChild(host);row.appendChild(timing);sec.querySelector("[data-components]").appendChild(row);buildExpandableMath(host,label,msg.value,COMPONENT_COLLAPSE_THRESHOLD);}
  function matrixSize(m){var t=0;m.forEach(function(r){r.forEach(function(x){t+=String(x).length;});});return t;}
  function summaryLabel(section){var map={metric:"g_{ij}",inverse:"g^{ij}",nonlinear:"N^i{}_j",deviation:"R^i{}_j",ricci:"R_{ij}",affineRicci:"\\bar R_{ij}"};return map[section]||"";}
  function addMatrixSummary(box,matrix,label){if(!label)return;if(matrixAllZero(matrix)){box.innerHTML='<div class="zero-summary">\\['+label+'=0\\]</div>';typeset(box);return;}var size=matrixSize(matrix),rows=matrix.map(function(r){return r.map(tex).join(" & ");}),formula=label+'=\\begin{pmatrix}'+rows.join(" \\\\ ")+'\\end{pmatrix}';var wrap=document.createElement("div");wrap.className="matrix-summary";box.appendChild(wrap);if(size<=SUMMARY_COLLAPSE_THRESHOLD){wrap.innerHTML='<div class="math-block">\\['+formula+'\\]</div>';typeset(wrap);return;}wrap.innerHTML='<div class="expression-summary"><div><strong>Completed matrix</strong><span>'+size.toLocaleString()+' expression characters</span></div><button type="button" class="expression-toggle" aria-expanded="false">Expand matrix</button></div><div class="expanded-expression" hidden><div class="sticky-collapse-bar"><button type="button" class="sticky-collapse-button">Collapse</button></div><div class="expanded-math-host"></div></div>';var b=wrap.querySelector(".expression-toggle"),e=wrap.querySelector(".expanded-expression"),mh=wrap.querySelector(".expanded-math-host"),st=wrap.querySelector(".sticky-collapse-button"),rendered=false;function toggle(open){if(open){if(!rendered){mh.innerHTML='<div class="math-block">\\['+formula+'\\]</div>';rendered=true;typeset(mh);}e.hidden=false;b.setAttribute("aria-expanded","true");b.textContent="Collapse matrix";}else{e.hidden=true;b.setAttribute("aria-expanded","false");b.textContent="Expand matrix";b.scrollIntoView({block:"nearest"});}}b.addEventListener("click",function(){toggle(b.getAttribute("aria-expanded")!=="true");});st.addEventListener("click",function(){toggle(false);});}
  function addVectorSummary(box,vector,label){if(!label)return;if(vector.every(isZeroValue)){box.innerHTML='<div class="zero-summary">\\['+label+'=0\\]</div>';typeset(box);return;}var formula=label+'=\\begin{pmatrix}'+vector.map(tex).join(" \\\\ ")+'\\end{pmatrix}';box.innerHTML='<div class="math-block">\\['+formula+'\\]</div>';typeset(box);}
  function renderSummary(sec,section,summary){if(!summary)return;var box=sec.querySelector("[data-summary]");if(summary.matrix)addMatrixSummary(box,summary.matrix,summaryLabel(section));if(summary.vector)addVectorSummary(box,summary.vector,section==="spray"?"G^i":"");if(summary.det){var h=document.createElement("div");h.className="scalar-summary";box.appendChild(h);buildExpandableMath(h,"\\det(g)",summary.det,SUMMARY_COLLAPSE_THRESHOLD);}}
  function sectionSelected(section){var key=SECTION_KEYS[section]||section;return activeDisplayOutputs[key]===true;}

  function handleMessage(event,token,ctx){if(token!==runToken)return;var raw=event.data||{},m=Object.assign({},raw);if(m.value!==undefined)m.value=displayExpression(m.value,ctx);if(m.summary)m.summary=translateSummary(m.summary,ctx);if(m.type==="path"){el("path-label").textContent=m.path;return;}if(m.type==="stepStart"){startLive(m.label);setStatus(m.label+"…","working");return;}if(m.type==="sectionStart"){if(sectionSelected(m.section))ensureSection(m.section,m.title,m.meta);return;}if(m.type==="component"){logTiming(displayLabel(m.label,ctx.coords)+" · "+fmt(m.elapsedMs)+(sectionSelected(m.section)?"":" · prerequisite / hidden"));if(sectionSelected(m.section)){ensureSection(m.section,m.section,m.meta);appendComponent(m,ctx);}return;}if(m.type==="sectionComplete"){logTiming((m.section||"section")+" completed · "+fmt(m.elapsedMs)+(sectionSelected(m.section)?"":" · prerequisite / hidden"));if(sectionSelected(m.section)){var sec=el("section-"+m.section);if(sec){var t=sec.querySelector("[data-time]");if(t)t.textContent=fmt(m.elapsedMs);renderSummary(sec,m.section,m.summary);var state=sectionState[m.section];if(state&&state.nonzero===0&&!m.summary)sec.querySelector("[data-empty]").hidden=false;}}return;}if(m.type==="done"){stopLive();el("live-step").textContent="Complete · total "+fmt(m.totalMs);setStatus("Calculation complete in "+fmt(m.totalMs)+".","success");setBusy(false);return;}if(m.type==="error"){stopLive();var message=m.message||"Calculation failed.";if(el("live-step"))el("live-step").textContent="Stopped · "+message;setStatus(message,"error");setBusy(false);return;}}
  function setBusy(on){qa("button,input,select,textarea",el("calculator-shell")).forEach(function(n){if(n.id==="clearResults"||n.closest("#results"))return;n.disabled=on;});if(el("clearResults"))el("clearResults").disabled=false;el("calculator-shell").classList.toggle("is-busy",on);}
  function run(){var data;try{data=payload();}catch(err){setStatus(err.message||String(err),"error");return;}activeDisplayOutputs=data.displayOutputs;if(worker)worker.terminate();worker=new Worker("finsler-worker-v4.js?v=5");runToken++;var token=runToken,ctx=data.context;prepareResults();setBusy(true);setStatus("Starting symbolic calculation…","working");startLive("Starting worker");worker.onmessage=function(e){handleMessage(e,token,ctx);};worker.onerror=function(e){if(token!==runToken)return;stopLive();setBusy(false);setStatus("Worker error: "+(e.message||"unknown error"),"error");};worker.postMessage(Object.assign({type:"calculate"},data.workerPayload));}
  function cancelCalculation(){if(worker){worker.terminate();worker=null;}runToken++;stopLive();setBusy(false);}
  function clearResults(){cancelCalculation();el("results").innerHTML="";setStatus("Ready.","");}

  function negateExpr(expr){var s=String(expr).trim();if(s==="0")return "0";try{return math.simplify("-("+s+")").toString({parenthesis:"auto"});}catch(e){return "-("+s+")";}}
  function normalizedCatalogueEntry(entry){var e=Object.assign({},entry);e.matrix=entry.matrix.map(function(r){return r.slice();});var flip=(entry.group==="Ansätze / pre-solutions")||(String(entry.group).indexOf("Catalogue ·")===0&&entry.id!=="sultana-dyer");if(flip)e.matrix=e.matrix.map(function(r){return r.map(negateExpr);});e.validation=PLUS_VALIDATION[entry.id]||entry.validation;e.signature=(String(entry.group).indexOf("Catalogue ·")===0||entry.group==="Ansätze / pre-solutions")?"+---":null;return e;}
  function catalogueGroups(items){var seen={},out=[];items.forEach(function(x){if(!seen[x.group]){seen[x.group]=1;out.push(x.group);}});return out;}
  function renderCatalogue(){var source=window.FINSLER_METRIC_CATALOGUE||[],items=source.map(normalizedCatalogueEntry),host=el("catalogueGrid"),search=el("catalogueSearch"),filter=el("catalogueGroup"),count=el("catalogueCount");if(!host||!search||!filter||!count)return;if(!items.length){count.textContent="Catalogue failed to load";host.innerHTML='<div class="catalogue-empty">Catalogue data could not be loaded.</div>';return;}if(!filter.dataset.ready){filter.innerHTML='<option value="">All groups</option>'+catalogueGroups(items).map(function(g){return '<option>'+esc(g)+'</option>';}).join("");filter.dataset.ready="1";search.addEventListener("input",renderCatalogue);filter.addEventListener("change",renderCatalogue);}var q=search.value.trim().toLowerCase(),g=filter.value,shown=items.filter(function(item){var hay=(item.title+" "+item.group+" "+item.description+" "+item.source).toLowerCase();return(!g||item.group===g)&&(!q||hay.indexOf(q)!==-1);});count.textContent=shown.length+" of "+items.length+" entries";host.innerHTML="";shown.forEach(function(item){var card=document.createElement("article");card.className="catalogue-card";card.innerHTML='<div class="catalogue-card-main"><div class="catalogue-card-top"><h4>'+esc(item.title)+'</h4><span class="catalogue-group">'+esc(item.group)+'</span></div><p>'+esc(item.description)+'</p><div class="catalogue-meta"><span class="catalogue-chip">'+esc(item.source)+'</span><span class="catalogue-chip">'+esc(item.coords.join(", "))+'</span>'+(item.signature?'<span class="catalogue-chip is-signature">'+item.signature+'</span>':'')+'<span class="catalogue-chip is-verified">'+esc(item.validation)+'</span></div></div><button type="button" class="catalogue-load">Load</button>';card.querySelector("button").addEventListener("click",function(){loadCatalogueEntry(item);});host.appendChild(card);});if(!shown.length)host.innerHTML='<div class="catalogue-empty">No matching metrics.</div>';}
  function inferForEntry(entry){activeDefinitions=entry.definitions||Object.create(null);inferNotation(entry.matrix.reduce(function(a,r){return a.concat(r);},[]));}
  function loadCatalogueEntry(entry){cancelCalculation();el("dimension").value=String(entry.dim);coordinateNames=entry.coords.slice();renderCoordinates(coordinateNames);resizeMatrix();resizeOneForm();setInputMode("metric");setGeometryMode("riemannian");activeCatalogueEntry=entry;activeDefinitions=entry.definitions||Object.create(null);setMatrix(entry.matrix);renderCoordinates(entry.coords);resizeOneForm();inferForEntry(entry);el("exampleNote").textContent=entry.title+" · "+entry.source+" · "+(entry.signature?"signature "+entry.signature+" · ":"")+"reference check: "+entry.validation+".";el("metricCatalogueDrawer").open=false;clearResults();setStatus("Catalogue metric loaded.","");}

  function loadQuickExample(){cancelCalculation();activeDefinitions=Object.create(null);activeCatalogueEntry=null;var v=el("exampleSelect").value;if(v==="randerspp"){el("dimension").value="4";coordinateNames=["u","v","x","y"];renderCoordinates(coordinateNames);resizeMatrix();resizeOneForm();setInputMode("metric");setGeometryMode("alphabeta");setMatrix([["-(x^2-y^2)","1","0","0"],["1","0","0","0"],["0","0","-1","0"],["0","0","0","-1"]]);setOneForm(["1","0","0","0"]);el("alphaBetaType").value="randers";el("exampleNote").textContent="Randers pp-wave in (+---): ds² = 2 du dv - H du² - dx² - dy², H=x²-y², β=du.";}else if(v==="ppwaveMetric4"){el("dimension").value="4";coordinateNames=["u","v","x","y"];renderCoordinates(coordinateNames);resizeMatrix();resizeOneForm();setInputMode("metric");setGeometryMode("riemannian");setMatrix([["-(x^2-y^2)","1","0","0"],["1","0","0","0"],["0","0","-1","0"],["0","0","0","-1"]]);el("exampleNote").textContent="Brinkmann pp-wave in (+---).";}else if(v==="mkropinaPP"){el("dimension").value="4";coordinateNames=["u","v","x","y"];renderCoordinates(coordinateNames);resizeMatrix();resizeOneForm();setInputMode("metric");setGeometryMode("alphabeta");setMatrix([["-(x^2-y^2)","1","0","0"],["1","0","0","0"],["0","0","-1","0"],["0","0","0","-1"]]);setOneForm(["1","0","0","0"]);el("alphaBetaType").value="mkropina";el("mParameter").value="1";el("exampleNote").textContent="m-Kropina pp-wave in (+---), β=du, default m=1.";}else if(v==="sphere3"){el("dimension").value="3";coordinateNames=["eta","phi","psi"];renderCoordinates(coordinateNames);resizeMatrix();resizeOneForm();setInputMode("metric");setGeometryMode("riemannian");setMatrix([["1","0","0"],["0","cos(eta)^2","0"],["0","0","sin(eta)^2"]]);el("exampleNote").textContent="Unit round S³ in Hopf coordinates.";}else if(v==="minkowski4"){el("dimension").value="4";coordinateNames=["t","x","y","z"];renderCoordinates(coordinateNames);resizeMatrix();resizeOneForm();setInputMode("metric");setGeometryMode("riemannian");setMatrix([["1","0","0","0"],["0","-1","0","0"],["0","0","-1","0"],["0","0","0","-1"]]);el("exampleNote").textContent="Minkowski metric with (+---) signature.";}else if(v==="finsler2"){el("dimension").value="2";coordinateNames=["x","y"];renderCoordinates(coordinateNames);resizeMatrix();resizeOneForm();setInputMode("lagrangian");el("lagrangian").value="(sqrt((1+x^2)*y_x^2 + y_y^2) + 0.15*y_y)^2";el("exampleNote").textContent="Direct two-dimensional Randers-type Lagrangian.";}updateAlphaBetaVisibility();inferNotation(collectRawExpressions());clearResults();setStatus("Example loaded.","");}

  function init(){renderCoordinates(coordinateNames);resizeMatrix();resizeOneForm();updateSelectionCount();updateMode();updateFormulaPreview();renderCatalogue();qa('input[name="inputMode"]').forEach(function(n){n.addEventListener("change",updateMode);});qa('input[name="geometryMode"]').forEach(function(n){n.addEventListener("change",updateAlphaBetaVisibility);});el("dimension").addEventListener("change",function(){var m=snapshotMatrix(),b=snapshotOneForm(),n=dimension();coordinateNames=coordinateNames.slice(0,n);while(coordinateNames.length<n)coordinateNames.push("x"+(coordinateNames.length+1));renderCoordinates(coordinateNames);resizeMatrix(m);resizeOneForm(b);});el("alphaBetaType").addEventListener("change",function(){updateMVisibility();updateFormulaPreview();});qa("[data-output]").forEach(function(n){n.addEventListener("change",updateSelectionCount);});el("selectAllOutputs").addEventListener("click",function(){setAllOutputs(true);});el("selectEssentials").addEventListener("click",selectEssentials);el("clearAllOutputs").addEventListener("click",function(){setAllOutputs(false);});el("calculateSelected").addEventListener("click",run);el("clearResults").addEventListener("click",clearResults);el("loadExample").addEventListener("click",loadQuickExample);el("detectNotation").addEventListener("click",function(){try{inferNotation(collectRawExpressions());setStatus("Constants and functions detected.","");}catch(e){setStatus(e.message,"error");}});el("metricCatalogueDrawer").addEventListener("toggle",function(){if(this.open)renderCatalogue();});loadQuickExample();}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();